
// Objective-C API for talking to the following Go packages
//
//	speedtest-go-app
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Speeder_FRAMEWORK_H__
#define __Speeder_FRAMEWORK_H__

#include "Speeder.objc.h"
#include "Universe.objc.h"

#endif
