// Objective-C API for talking to speedtest-go-app Go package.
//   gobind -lang=objc speedtest-go-app
//
// File is generated by gobind. Do not edit.

#ifndef __Speeder_H__
#define __Speeder_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT void SpeederDoTest(void);

#endif
