// Objective-C API for talking to speedtest-go-app Go package.
//   gobind -lang=objc speedtest-go-app
//
// File is generated by gobind. Do not edit.

#ifndef __Speedmeasure_H__
#define __Speedmeasure_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@protocol SpeedmeasureOnProgressHandler;
@class SpeedmeasureOnProgressHandler;
@protocol SpeedmeasureOnReadyHandler;
@class SpeedmeasureOnReadyHandler;
@protocol SpeedmeasureOnTestFinishHandler;
@class SpeedmeasureOnTestFinishHandler;
@protocol SpeedmeasureOnTestStartHandler;
@class SpeedmeasureOnTestStartHandler;

@protocol SpeedmeasureOnProgressHandler <NSObject>
- (void)handle:(NSString* _Nullable)test result:(double)result progress:(double)progress;
@end

@protocol SpeedmeasureOnReadyHandler <NSObject>
- (void)handle;
@end

@protocol SpeedmeasureOnTestFinishHandler <NSObject>
- (void)handle:(NSString* _Nullable)test result:(double)result;
@end

@protocol SpeedmeasureOnTestStartHandler <NSObject>
- (void)handle:(NSString* _Nullable)test;
@end

FOUNDATION_EXPORT NSString* _Nonnull const SpeedmeasureTestDownload;
FOUNDATION_EXPORT NSString* _Nonnull const SpeedmeasureTestPing;
FOUNDATION_EXPORT NSString* _Nonnull const SpeedmeasureTestUpload;

FOUNDATION_EXPORT int64_t SpeedmeasurePing(NSString* _Nullable hostname, long timeout);

FOUNDATION_EXPORT NSString* _Nonnull SpeedmeasureRun(NSString* _Nullable Tests, id<SpeedmeasureOnReadyHandler> _Nullable OnReadyHandler, id<SpeedmeasureOnTestStartHandler> _Nullable OnTestStartHandler, id<SpeedmeasureOnTestFinishHandler> _Nullable OnTestFinishHandler, id<SpeedmeasureOnProgressHandler> _Nullable OnProgressHandler);

@class SpeedmeasureOnProgressHandler;

@class SpeedmeasureOnReadyHandler;

@class SpeedmeasureOnTestFinishHandler;

@class SpeedmeasureOnTestStartHandler;

@interface SpeedmeasureOnProgressHandler : NSObject <goSeqRefInterface, SpeedmeasureOnProgressHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)handle:(NSString* _Nullable)test result:(double)result progress:(double)progress;
@end

@interface SpeedmeasureOnReadyHandler : NSObject <goSeqRefInterface, SpeedmeasureOnReadyHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)handle;
@end

@interface SpeedmeasureOnTestFinishHandler : NSObject <goSeqRefInterface, SpeedmeasureOnTestFinishHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)handle:(NSString* _Nullable)test result:(double)result;
@end

@interface SpeedmeasureOnTestStartHandler : NSObject <goSeqRefInterface, SpeedmeasureOnTestStartHandler> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)handle:(NSString* _Nullable)test;
@end

#endif
